In [3]:
import pandas as pd
df=pd.read_csv(r"C:\Users\ngkna\OneDrive\Documents\Data Science\Cognify Data Science\Dataset .csv")
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [4]:
df["Has Table booking"]=df["Has Table booking"].map({'Yes':1,'No':0})

In [5]:
df["Has Online delivery"]=df["Has Online delivery"].map({'Yes':1,'No':0})

In [6]:
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),1,0,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),1,0,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),1,0,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),0,0,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),1,0,No,No,4,4.8,Dark Green,Excellent,229

In [12]:
x = df[["Price range","Votes","Longitude","Latitude","Has Table booking","Has Online delivery"]]
y = df["Aggregate rating"]

In [21]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_squared_error

In [22]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=10)

In [26]:
model1=LinearRegression()
model1.fit(x_train,y_train)
y_pred_1=model1.predict(x_test)
r2_1=r2_score(y_test,y_pred_1)
rmse_1=np.sqrt(mean_squared_error(y_test,y_pred_1))

print("Linear Regression R2:", r2_1)
print("Linear Regression RMSE:", rmse_1)

Linear Regression R2: 0.27585655114666363
Linear Regression RMSE: 1.282266657565157

In [37]:
model2=DecisionTreeRegressor(random_state=10)
model2.fit(x_train,y_train)
y_pred_2=model2.predict(x_test)
r2_2=r2_score(y_test,y_pred_2)
rmse_2=np.sqrt(mean_squared_error(y_test,y_pred_2))

print("Decision Tree R2 :", r2_2)
print("Decision Tree RMSE :", rmse_2)

Decision Tree R2 : 0.9208837777540325
Decision Tree RMSE : 0.42383695166729113

In [40]:
model3=RandomForestRegressor(random_state=10)
model3.fit(x_train,y_train)
y_pred_3=model3.predict(x_test)
r2_3=r2_score(y_test,y_pred_3)
rmse_3=np.sqrt(mean_squared_error(y_test,y_pred_3))

print("Random Forest R2 :", r2_2)
print("Random Forest RMSE :", rmse_2)

Random Forest R2 : 0.9208837777540325
Random Forest RMSE : 0.42383695166729113

In [44]:
results = pd.DataFrame({
    "Model": ["Linear Regression", "Decision Tree", "Random Forest"],
    "R2 Score": [r2_1, r2_2, r2_3],
    "RMSE": [rmse_1, rmse_2, rmse_3]
})

print(results)

               Model  R2 Score      RMSE
0  Linear Regression  0.275857  1.282267
1      Decision Tree  0.920884  0.423837
2      Random Forest  0.954886  0.320051